import { useState, useMemo } from "react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Code2, Copy, Download, FileCode, CheckCircle } from "lucide-react";
import { toast } from "sonner";

function generatePlaywrightTS(nodes: any[]): string {
  const lines = [
    `import { test, expect } from '@playwright/test';`,
    ``,
    `test('Momentum Studio Generated Test', async ({ page }) => {`,
  ];
  for (const node of nodes) {
    switch (node.type) {
      case "navigate":
        lines.push(`  await page.goto('${node.data.url || "https://example.com"}');`);
        break;
      case "click":
        lines.push(`  await page.click('${node.data.selector || "button"}');`);
        break;
      case "type":
        lines.push(`  await page.fill('${node.data.selector || "input"}', '${node.data.text || ""}');`);
        break;
      case "wait":
        lines.push(`  await page.waitForTimeout(${node.data.duration || 1000});`);
        break;
      case "screenshot":
        lines.push(`  await page.screenshot({ path: 'screenshot-${node.id}.png' });`);
        break;
      case "condition":
        lines.push(`  // Condition: ${node.data.expression || "check element"}`);
        lines.push(`  const isVisible = await page.isVisible('${node.data.selector || "body"}');`);
        lines.push(`  expect(isVisible).toBeTruthy();`);
        break;
      case "loop":
        lines.push(`  for (let i = 0; i < ${node.data.iterations || 5}; i++) {`);
        lines.push(`    // Loop iteration \${i + 1}`);
        lines.push(`  }`);
        break;
    }
  }
  lines.push(`});`);
  return lines.join("\n");
}

function generatePlaywrightPython(nodes: any[]): string {
  const lines = [
    `import pytest`,
    `from playwright.sync_api import Page, expect`,
    ``,
    `def test_momentum_studio_generated(page: Page):`,
    `    """Generated by Momentum Studio"""`,
  ];
  for (const node of nodes) {
    switch (node.type) {
      case "navigate":
        lines.push(`    page.goto("${node.data.url || "https://example.com"}")`);
        break;
      case "click":
        lines.push(`    page.click("${node.data.selector || "button"}")`);
        break;
      case "type":
        lines.push(`    page.fill("${node.data.selector || "input"}", "${node.data.text || ""}")`);
        break;
      case "wait":
        lines.push(`    page.wait_for_timeout(${node.data.duration || 1000})`);
        break;
      case "screenshot":
        lines.push(`    page.screenshot(path="screenshot-${node.id}.png")`);
        break;
      case "condition":
        lines.push(`    # Condition: ${node.data.expression || "check element"}`);
        lines.push(`    expect(page.locator("${node.data.selector || "body"}")).to_be_visible()`);
        break;
      case "loop":
        lines.push(`    for i in range(${node.data.iterations || 5}):`);
        lines.push(`        pass  # Loop iteration`);
        break;
    }
  }
  return lines.join("\n");
}

function generateCypress(nodes: any[]): string {
  const lines = [
    `describe('Momentum Studio Generated Test', () => {`,
    `  it('should execute automation workflow', () => {`,
  ];
  for (const node of nodes) {
    switch (node.type) {
      case "navigate":
        lines.push(`    cy.visit('${node.data.url || "https://example.com"}');`);
        break;
      case "click":
        lines.push(`    cy.get('${node.data.selector || "button"}').click();`);
        break;
      case "type":
        lines.push(`    cy.get('${node.data.selector || "input"}').type('${node.data.text || ""}');`);
        break;
      case "wait":
        lines.push(`    cy.wait(${node.data.duration || 1000});`);
        break;
      case "screenshot":
        lines.push(`    cy.screenshot('screenshot-${node.id}');`);
        break;
      case "condition":
        lines.push(`    cy.get('${node.data.selector || "body"}').should('be.visible');`);
        break;
      case "loop":
        lines.push(`    Cypress._.times(${node.data.iterations || 5}, (i) => {`);
        lines.push(`      // Loop iteration`);
        lines.push(`    });`);
        break;
    }
  }
  lines.push(`  });`);
  lines.push(`});`);
  return lines.join("\n");
}

export default function CodeGenerator() {
  const [selectedScript, setSelectedScript] = useState<string>("");
  const [framework, setFramework] = useState("playwright-ts");
  const [copied, setCopied] = useState(false);

  const { data: scriptsList } = trpc.scripts.list.useQuery();

  const selectedScriptData = useMemo(() => {
    if (!selectedScript || !scriptsList) return null;
    return scriptsList.find((s) => s.id.toString() === selectedScript);
  }, [selectedScript, scriptsList]);

  const generatedCode = useMemo(() => {
    if (!selectedScriptData) return "// Select a script to generate code";
    const nodes = (selectedScriptData.nodes as any[]) || [];
    switch (framework) {
      case "playwright-ts":
        return generatePlaywrightTS(nodes);
      case "playwright-py":
        return generatePlaywrightPython(nodes);
      case "cypress":
        return generateCypress(nodes);
      default:
        return "// Select a framework";
    }
  }, [selectedScriptData, framework]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    toast.success("Code copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = framework === "playwright-py" ? ".py" : ".ts";
    const prefix = framework === "cypress" ? "cypress_test" : "playwright_test";
    const blob = new Blob([generatedCode], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${prefix}${ext}`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("File downloaded");
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
          <Code2 className="h-6 w-6 text-primary" />
          Code Generator
        </h1>
        <p className="text-muted-foreground mt-1">
          Export your visual scripts as production-ready Playwright or Cypress test files
        </p>
      </div>

      {/* Controls */}
      <div className="flex items-center gap-4">
        <div className="flex-1 max-w-xs">
          <Select value={selectedScript} onValueChange={setSelectedScript}>
            <SelectTrigger>
              <SelectValue placeholder="Select a script..." />
            </SelectTrigger>
            <SelectContent>
              {scriptsList?.map((s) => (
                <SelectItem key={s.id} value={s.id.toString()}>
                  {s.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <Tabs value={framework} onValueChange={setFramework}>
          <TabsList>
            <TabsTrigger value="playwright-ts">Playwright TS</TabsTrigger>
            <TabsTrigger value="playwright-py">Playwright Python</TabsTrigger>
            <TabsTrigger value="cypress">Cypress</TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {/* Code Output */}
      <Card className="bg-card border-border">
        <CardHeader className="pb-2 flex flex-row items-center justify-between">
          <CardTitle className="text-base font-semibold flex items-center gap-2">
            <FileCode className="h-4 w-4 text-primary" />
            Generated Code
            <Badge variant="outline" className="text-xs ml-2">
              {framework === "playwright-ts"
                ? "TypeScript"
                : framework === "playwright-py"
                  ? "Python"
                  : "JavaScript"}
            </Badge>
          </CardTitle>
          <div className="flex items-center gap-2">
            <Button size="sm" variant="outline" onClick={handleCopy}>
              {copied ? (
                <CheckCircle className="h-3.5 w-3.5 mr-1 text-green-500" />
              ) : (
                <Copy className="h-3.5 w-3.5 mr-1" />
              )}
              {copied ? "Copied" : "Copy"}
            </Button>
            <Button size="sm" variant="outline" onClick={handleDownload}>
              <Download className="h-3.5 w-3.5 mr-1" />
              Download
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <pre className="bg-secondary/50 rounded-lg p-4 overflow-x-auto text-sm font-mono text-foreground leading-relaxed max-h-[500px] overflow-y-auto">
            <code>{generatedCode}</code>
          </pre>
        </CardContent>
      </Card>

      {/* Info */}
      {!selectedScript && (
        <Card className="bg-card border-border">
          <CardContent className="py-12 text-center">
            <Code2 className="h-12 w-12 mx-auto text-muted-foreground/30 mb-3" />
            <p className="text-muted-foreground">Select a script to generate code</p>
            <p className="text-xs text-muted-foreground/60 mt-1">
              Build a workflow in the Script Builder first, then export it here as Playwright or Cypress code
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
